run_power: power.o test-power.o
	gcc -o run_power power.o test-power.o -Wall -Wextra --pedantic --std=gnu99

power.o: power.c
	gcc -Wall -Wextra --pedantic --std=gnu99 -c power.c

test-power.o: test-power.c
	gcc -Wall -Wextra --pedantic --std=gnu99 -c test-power.c
